### ISSUE TITLE
Important problem with inserting View Controllers inside Scroll View!

### ISSUE THREAD

**Issue by jeudesprits** [davedelong/MVCTodo#3]
Your idea is beautiful. I'm amazed how easy and affordable my code is now. But recently I stumbled upon one annoying nuisance. Often it is necessary to insert Table Views and Collection Views inside the Scroll Views. And to make it all work perfectly, you need to stretch our Table Views or Collection Views to their full height, which completely kills reuse Cells. How to be in this situation?

**Comment by ArkadiYoskovitz** [comment]
Why do you need to insert a table view into a scroll view ?

This might be an idea that someone implemented for a quick and dearty bugfix tant fixated into a pattern. As you noted this kills cell reuse. Not sure why you even need this (table in scroll)

**Comment by jeudesprits** [comment]
> Why do you need to insert a table view into a scroll view ?
> 
> This might be an idea that someone implemented for a quick and dearty bugfix tant fixated into a pattern. As you noted this kills cell reuse. Not sure why you even need this (table in scroll)

Such a banner on top cannot be made as a Table Header View. Need a parallax effect and so on. 

![Example1](https://user-images.githubusercontent.com/36597778/50426285-0ef75c80-08ac-11e9-8ea8-76c838e1ca67.png)

or

![Example3](https://user-images.githubusercontent.com/36597778/50426397-92b24880-08ae-11e9-9545-dccf2bb6c43c.PNG)

**Comment by ArkadiYoskovitz** [comment]
@jeudesprits take a look at the following link, the author shows how you can do what you need without doing a table in scroll view

https://medium.com/if-let-swift-programming/how-to-create-a-stretchable-tableviewheader-in-ios-ee9ed049aba3

**Comment by jeudesprits** [comment]
> @jeudesprits take a look at the following link, the author shows how you can do what you need without doing a table in scroll view
> 
> https://medium.com/if-let-swift-programming/how-to-create-a-stretchable-tableviewheader-in-ios-ee9ed049aba3



It is absolutely not that. Look at my two screenshots again.

**Comment by davedelong** [comment]
This discussion, while interesting, doesn't have anything to do with the "MVCTodo" sample code.

**Comment by jeudesprits** [comment]
> This discussion, while interesting, doesn't have anything to do with the "MVCTodo" sample code.

Sorry, but I did not find where to write you about this issue. All the same, this example affects exactly your idea of MVC Evolution.
